node('nodejs') {
  stage 'build'
  openshiftBuild(buildConfig: 'bios-association-table-app', showBuildLogs: 'true')
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'bios-association-table-app')
}
